Simulation = "TransferCoins"
Servers = 2
Bf = 4
Rounds = 1
RunWait = "6000s"
Suite = "Ed25519"

Keep,   Transactions, BatchSize,  Hosts,  Delay, BlockInterval
true,   2000,         20,          20,    30,    "10s"